### ISSUE TITLE
App fails with error

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/LAI-Flashy-App#60]
I ran the app from the gallery and got this error:

```
opriate Weights Enum instead.
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.153Z   warnings.warn(
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z Traceback (most recent call last):
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     sys.exit(main())
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return self.main(*args, **kwargs)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1059, in main
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     rv = self.invoke(ctx)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return ctx.invoke(self.callback, **ctx.params)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 767, in invoke
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return __callback(*args, **kwargs)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 86, in run_work
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     run_lightning_work(
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 49, in wrapper
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     res = func(*args, **kwargs)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 73, in wrapper
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     res = func(*args, **kwargs)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 118, in run_lightning_work
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     WorkRunner(
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 308, in __call__
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     raise e
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 291, in __call__
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     self.run_once()
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 400, in run_once
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     self.work.on_exception(e)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/work.py", line 471, in on_exception
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     raise exception
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 391, in run_once
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     ret = work_run(*args, **kwargs)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/flashy/components/flash_trainer.py", line 99, in run
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     super().run()
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/components/python/tracer.py", line 115, in run
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     res = self._run_tracer(init_globals)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/flashy/components/flash_trainer.py", line 104, in _run_tracer
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return tracer.trace(
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/tracer.py", line 169, in trace
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     res = runpy.run_path(script, run_name="__main__", init_globals=init_globals or globals())
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/usr/lib/python3.8/runpy.py", line 265, in run_path
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     return _run_module_code(code, init_globals, run_name,
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     _run_code(code, mod_globals, init_globals,
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     exec(code, run_globals)
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/tmp/tmpqichao3z/flash_training.py", line 35, in <module>
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     model = ImageClassifier(
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z   File "/content/venv/lib/python3.8/site-packages/flash/image/classification/model.py", line 118, in __init__
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z     raise MisconfigurationException("`num_classes` or `labels` should be provided.")
[root.hpo.runs.eb8431d930ac4b118f1b577daa303a8d] 2022-08-02T20:50:35.156Z pytorch_lightning.utilities.exceptions.MisconfigurationException: `num_classes` or `labels` should be provided.
```

**Comment by manskx** [comment]
This error happens if the app starts with the default inputs without selecting `Train folder` or `Validation folder`. An improvement can be done here to have validation on these fields
